org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=false
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.suppressGradlePluginWarnings=DeprecatedGradleVersionWarning
android.includeDependencyInfoInApks=false
android.enableR8.fullMode=true
